name = "luukslab"
main = "./.svelte-kit/cloudflare-workers/index.js"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2025-06-23"

# site = { bucket = "./static" }

[assets]
binding = "ASSETS"
directory = ".svelte-kit/cloudflare"

[[d1_databases]]
binding = "DB"
database_name = "kablan_db"
database_id = "9f574478-68a9-4227-bd02-98f629ea6147"
migrations_dir = "./drizzle"